//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWarehouse.ServiceShop {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ShopServer")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Err {
            get {
                return this.ErrField;
            }
            set {
                if ((this.ErrField.Equals(value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Good", Namespace="http://schemas.datacontract.org/2004/07/ShopServer")]
    [System.SerializableAttribute()]
    public partial struct Good : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idWareField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateIn {
            get {
                return this.DateInField;
            }
            set {
                if ((this.DateInField.Equals(value) != true)) {
                    this.DateInField = value;
                    this.RaisePropertyChanged("DateIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Err {
            get {
                return this.ErrField;
            }
            set {
                if ((this.ErrField.Equals(value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceIn {
            get {
                return this.PriceInField;
            }
            set {
                if ((this.PriceInField.Equals(value) != true)) {
                    this.PriceInField = value;
                    this.RaisePropertyChanged("PriceIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceOut {
            get {
                return this.PriceOutField;
            }
            set {
                if ((this.PriceOutField.Equals(value) != true)) {
                    this.PriceOutField = value;
                    this.RaisePropertyChanged("PriceOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idWare {
            get {
                return this.idWareField;
            }
            set {
                if ((this.idWareField.Equals(value) != true)) {
                    this.idWareField = value;
                    this.RaisePropertyChanged("idWare");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CashOperation", Namespace="http://schemas.datacontract.org/2004/07/ShopServer")]
    [System.SerializableAttribute()]
    public partial struct CashOperation : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CashBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeOpertionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeOperationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceOperation {
            get {
                return this.PriceOperationField;
            }
            set {
                if ((this.PriceOperationField.Equals(value) != true)) {
                    this.PriceOperationField = value;
                    this.RaisePropertyChanged("PriceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeOpertion {
            get {
                return this.TimeOpertionField;
            }
            set {
                if ((this.TimeOpertionField.Equals(value) != true)) {
                    this.TimeOpertionField = value;
                    this.RaisePropertyChanged("TimeOpertion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeOperation {
            get {
                return this.TypeOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOperationField, value) != true)) {
                    this.TypeOperationField = value;
                    this.RaisePropertyChanged("TypeOperation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceShop.IShop")]
    public interface IShop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/UserAuth", ReplyAction="http://tempuri.org/IShop/UserAuthResponse")]
        ShopWarehouse.ServiceShop.User UserAuth(string Login, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetAllUsers", ReplyAction="http://tempuri.org/IShop/GetAllUsersResponse")]
        ShopWarehouse.ServiceShop.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddUser", ReplyAction="http://tempuri.org/IShop/AddUserResponse")]
        void AddUser(ShopWarehouse.ServiceShop.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetRoles", ReplyAction="http://tempuri.org/IShop/GetRolesResponse")]
        string[] GetRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddCategory", ReplyAction="http://tempuri.org/IShop/AddCategoryResponse")]
        void AddCategory(string[] Cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetCategoryes", ReplyAction="http://tempuri.org/IShop/GetCategoryesResponse")]
        string[] GetCategoryes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddGood", ReplyAction="http://tempuri.org/IShop/AddGoodResponse")]
        void AddGood(string Name, string Categoryes, string Barcode, double PriceOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddGoods", ReplyAction="http://tempuri.org/IShop/AddGoodsResponse")]
        void AddGoods(int idGoods, int Count, double PriceIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetGood", ReplyAction="http://tempuri.org/IShop/GetGoodResponse")]
        ShopWarehouse.ServiceShop.Good GetGood(string Barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/SellGoods", ReplyAction="http://tempuri.org/IShop/SellGoodsResponse")]
        void SellGoods(ShopWarehouse.ServiceShop.Good[] goods, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetAllGoods", ReplyAction="http://tempuri.org/IShop/GetAllGoodsResponse")]
        ShopWarehouse.ServiceShop.Good[] GetAllGoods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetGoodsBalance", ReplyAction="http://tempuri.org/IShop/GetGoodsBalanceResponse")]
        ShopWarehouse.ServiceShop.Good[] GetGoodsBalance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetGoodsToDay", ReplyAction="http://tempuri.org/IShop/GetGoodsToDayResponse")]
        ShopWarehouse.ServiceShop.Good[] GetGoodsToDay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/DeleteBalance", ReplyAction="http://tempuri.org/IShop/DeleteBalanceResponse")]
        void DeleteBalance(int idWare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetToDayOperations", ReplyAction="http://tempuri.org/IShop/GetToDayOperationsResponse")]
        ShopWarehouse.ServiceShop.CashOperation[] GetToDayOperations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetGoodsOperations", ReplyAction="http://tempuri.org/IShop/GetGoodsOperationsResponse")]
        ShopWarehouse.ServiceShop.Good[] GetGoodsOperations(int idOperation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/CashIn", ReplyAction="http://tempuri.org/IShop/CashInResponse")]
        void CashIn(double Cash, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/CashOut", ReplyAction="http://tempuri.org/IShop/CashOutResponse")]
        void CashOut(double Cash, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetStartBalance", ReplyAction="http://tempuri.org/IShop/GetStartBalanceResponse")]
        double GetStartBalance();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopChannel : ShopWarehouse.ServiceShop.IShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopClient : System.ServiceModel.ClientBase<ShopWarehouse.ServiceShop.IShop>, ShopWarehouse.ServiceShop.IShop {
        
        public ShopClient() {
        }
        
        public ShopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShopWarehouse.ServiceShop.User UserAuth(string Login, string Pass) {
            return base.Channel.UserAuth(Login, Pass);
        }
        
        public ShopWarehouse.ServiceShop.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public void AddUser(ShopWarehouse.ServiceShop.User user) {
            base.Channel.AddUser(user);
        }
        
        public string[] GetRoles() {
            return base.Channel.GetRoles();
        }
        
        public void AddCategory(string[] Cat) {
            base.Channel.AddCategory(Cat);
        }
        
        public string[] GetCategoryes() {
            return base.Channel.GetCategoryes();
        }
        
        public void AddGood(string Name, string Categoryes, string Barcode, double PriceOut) {
            base.Channel.AddGood(Name, Categoryes, Barcode, PriceOut);
        }
        
        public void AddGoods(int idGoods, int Count, double PriceIn) {
            base.Channel.AddGoods(idGoods, Count, PriceIn);
        }
        
        public ShopWarehouse.ServiceShop.Good GetGood(string Barcode) {
            return base.Channel.GetGood(Barcode);
        }
        
        public void SellGoods(ShopWarehouse.ServiceShop.Good[] goods, int idUser) {
            base.Channel.SellGoods(goods, idUser);
        }
        
        public ShopWarehouse.ServiceShop.Good[] GetAllGoods() {
            return base.Channel.GetAllGoods();
        }
        
        public ShopWarehouse.ServiceShop.Good[] GetGoodsBalance() {
            return base.Channel.GetGoodsBalance();
        }
        
        public ShopWarehouse.ServiceShop.Good[] GetGoodsToDay() {
            return base.Channel.GetGoodsToDay();
        }
        
        public void DeleteBalance(int idWare) {
            base.Channel.DeleteBalance(idWare);
        }
        
        public ShopWarehouse.ServiceShop.CashOperation[] GetToDayOperations() {
            return base.Channel.GetToDayOperations();
        }
        
        public ShopWarehouse.ServiceShop.Good[] GetGoodsOperations(int idOperation) {
            return base.Channel.GetGoodsOperations(idOperation);
        }
        
        public void CashIn(double Cash, int idUser) {
            base.Channel.CashIn(Cash, idUser);
        }
        
        public void CashOut(double Cash, int idUser) {
            base.Channel.CashOut(Cash, idUser);
        }
        
        public double GetStartBalance() {
            return base.Channel.GetStartBalance();
        }
    }
}
